# Generated by Django 4.2.19 on 2025-02-12 17:58

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='NOME COMPLETO (Nome Social para pessoas transgênero):\t', max_length=80, verbose_name='Nome')),
                ('slug', models.SlugField(help_text='Slug do seu post (para URLs)', max_length=255, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data_criação')),
                ('birthday', models.DateTimeField(null=True, verbose_name='nascimento')),
                ('cpf', models.PositiveSmallIntegerField(unique=True, verbose_name='CPF')),
                ('rg', models.PositiveSmallIntegerField(verbose_name='RG')),
                ('age', models.CharField(choices=[('15', 'anos ou menos'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25 anos ou mais')], default='15', help_text='Clique para selecionar', max_length=50, verbose_name='idade')),
                ('gender', models.CharField(default='MC', help_text='Clique para selecionar', max_length=50, verbose_name='genero')),
                ('ethnicity', models.CharField(default='OUT', help_text='Clique para selecionar', max_length=50, verbose_name='etinia')),
                ('ethnicity_other', models.CharField(blank=True, help_text='Em caso de outra etinia favor informa-la', max_length=80, verbose_name='etinia')),
                ('address', models.CharField(help_text='Endereço', max_length=80, verbose_name='Endereço')),
                ('address_line_1', models.CharField(help_text='Complemento', max_length=80, verbose_name='Complemento')),
                ('neighberhood', models.CharField(help_text='Bairro', max_length=80, verbose_name='Bairro')),
                ('city', models.CharField(default='RJ', help_text='Clique para selecionar', max_length=50, verbose_name='city')),
                ('city_other', models.CharField(blank=True, help_text='Em caso de outra cidade favor informa-la', max_length=80, verbose_name='Outra_cidade')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telefone')),
                ('whatsapp', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Whatsapp')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('zipcode', models.CharField(blank=True, help_text='CEP do usuário', max_length=20, null=True)),
                ('parent', models.CharField(blank=True, help_text='Nome completo do responsável ', max_length=80, verbose_name='Responsalvel')),
                ('parent_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Telefone')),
                ('scholl_level', models.CharField(default='EFIPU', help_text='NÍVEL DE ESCOLARIDADE:', max_length=50, verbose_name='escolaridade')),
                ('school', models.CharField(help_text='INSTITUIÇÃO DE ENSINO:', max_length=80, verbose_name='Escola')),
                ('grade', models.CharField(help_text='SE ESTIVER ESTUDANDO NESTE ANO, INFORME SÉRIE / PERÍODO:', max_length=80, verbose_name='Série')),
                ('studing', models.CharField(default='MAN', help_text='SE ESTIVER ESTUDANDO NESTE ANO, INFORME SÉRIE / PERÍODO:', max_length=50, verbose_name='período')),
                ('course', models.CharField(blank=True, help_text='CURSO (CASO ESTEJA NA ESCOLA TÉCNICA OU NA FACULDADE):', max_length=80, verbose_name='Curso')),
                ('intern', models.BooleanField(default=False, verbose_name='Estágio')),
                ('intern_time', models.CharField(blank=True, help_text='CEM QUAIS HORÁRIOS VOCÊ TRABALHA OU FAZ ESTÁGIO? ', max_length=80, verbose_name='horarios')),
                ('looking_work', models.BooleanField(default=False, verbose_name='trabalho')),
                ('income', models.CharField(default='TO1', help_text='RENDA FAMILIAR MENSAL', max_length=50, verbose_name='renda')),
                ('family', models.CharField(default='2', help_text='Clique para selecionar', max_length=50, verbose_name='familia')),
                ('deficincy', models.BooleanField(default=False, verbose_name='deficiente')),
                ('deficincy_type', models.CharField(blank=True, help_text='VOCÊ POSSUI ALGUM TIPO DE DEFICIÊNCIA? SE SIM, PODERIA NOS DIZER QUAL?', max_length=80, verbose_name='deficiencia')),
                ('special_need', models.BooleanField(default=False, verbose_name='cuidado_especial')),
                ('special_interview', models.CharField(blank=True, help_text='SE SIM, PODERIA NOS DIZER QUAL?', max_length=80, verbose_name='cuidado_entrevista')),
                ('knowloge', models.CharField(default='OT', help_text='Clique para selecionar', max_length=50, verbose_name='conhecia')),
                ('knowloge_other', models.CharField(blank=True, help_text='COMO VOCÊ FICOU SABENDO DAS INSCRIÇÕES PARA O PROCESSO SELETIVO DESTE ANO? ', max_length=80, verbose_name='conhecimento')),
                ('prior_inscription', models.CharField(default='ES', help_text='Clique para selecionar', max_length=50, verbose_name='conhecia')),
                ('prior_course', models.BooleanField(default=False, verbose_name='curso_anterior')),
                ('dedication', models.BooleanField(default=False, verbose_name='dedicação')),
                ('tablet', models.CharField(default='OK', help_text='Clique para selecionar', max_length=50, verbose_name='tablet')),
                ('likes_to_draw', models.BooleanField(default=False, verbose_name='desenha')),
                ('frequency', models.CharField(default='MON', help_text='Clique para selecionar', max_length=50, verbose_name='frequencia')),
                ('group_rating', models.PositiveIntegerField(default=10, help_text='Numa escala de 0 à 10, o quanto você gosta de trabalhar em grupo?', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='grupo')),
                ('critics', models.CharField(help_text='COMO VOCÊ LIDA COM CRÍTICAS EM RELAÇÃO AO SEU TRABALHO?', max_length=80, verbose_name='criticas')),
                ('previous_work', models.CharField(help_text='HÁ OUTRA COISA QUE VOCÊ JÁ FEZ RELACIONADA À ANIMAÇÃO / AUDIOVISUAL QUE GOSTARIA DE DESTACAR?', max_length=80, verbose_name='experiencia')),
                ('message', models.CharField(help_text='USE AS LINHAS ABAIXO PARA DAR SEU RECADO: POR QUE VOCÊ SE INTERESSOU EM PARTICIPAR DO ESTÚDIO ESCOLA?', max_length=80, verbose_name='recado')),
                ('portifolio', models.CharField(help_text='VOCÊ POSSUI UM LOCAL ONDE DIVULGA SEU TRABALHO ARTÍSTICO? EM CASO AFIRMATIVO COMPARTILHE O LINK COM A GENTE!', max_length=80, verbose_name='portifolio')),
            ],
        ),
    ]
