# Generated by Django 4.2.19 on 2025-02-12 18:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='slug',
        ),
        migrations.AddField(
            model_name='inscription',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file_uploads/'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='gender_other',
            field=models.CharField(blank=True, help_text='em casa de outro:', max_length=80, null=True, verbose_name='genero_outro'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='prior_course_year',
            field=models.CharField(blank=True, max_length=50, verbose_name='curso_anterior'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='age',
            field=models.CharField(default='15', help_text='Clique para selecionar', max_length=50, verbose_name='idade'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='dedication',
            field=models.CharField(max_length=50, verbose_name='dedicação'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='deficincy',
            field=models.CharField(max_length=50, verbose_name='deficiente'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='ethnicity',
            field=models.CharField(blank=True, default='OUT', help_text='Clique para selecionar', max_length=50, null=True, verbose_name='etinia'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='gender',
            field=models.CharField(choices=[('MC', 'Mulher cis'), ('MT', 'Mulher trans'), ('HC', 'Homem cis'), ('HT', 'Homem trans'), ('NB', 'Não binário'), ('OUT', 'Outra')], default='MC', help_text='Clique para selecionar', max_length=50, verbose_name='genero'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='intern',
            field=models.CharField(max_length=50, verbose_name='Estágio'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='knowloge',
            field=models.CharField(default='outros', help_text='Clique para selecionar', max_length=50, verbose_name='conhecia'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='likes_to_draw',
            field=models.CharField(max_length=50, verbose_name='desenha'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='looking_work',
            field=models.CharField(max_length=50, verbose_name='trabalho'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='parent_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=50, region=None, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='prior_course',
            field=models.CharField(blank=True, max_length=50, verbose_name='curso_anterior'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='prior_inscription',
            field=models.CharField(default='2012', help_text='Clique para selecionar', max_length=50, verbose_name='conhecia'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='scholl_level',
            field=models.CharField(default='', help_text='NÍVEL DE ESCOLARIDADE:', max_length=50, verbose_name='escolaridade'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='special_need',
            field=models.CharField(max_length=50, verbose_name='cuidado_especial'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='tablet',
            field=models.CharField(default='OK', help_text='Clique para selecionar', max_length=100, verbose_name='tablet'),
        ),
    ]
