# Generated by Django 4.2.19 on 2025-02-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0003_alter_inscription_knowloge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='prior_inscription',
            field=models.CharField(default='2012', help_text='Clique para selecionar', max_length=80, verbose_name='inscricao_anterior'),
        ),
    ]
