# Generated by Django 4.2.19 on 2025-02-21 11:24

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0004_alter_inscription_prior_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='address',
            field=models.CharField(default=' ', help_text='Endereço', max_length=80, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='address_line_1',
            field=models.CharField(default=' ', help_text='Complemento', max_length=80, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='city',
            field=models.CharField(default='Rio de Janeiro', help_text='Clique para selecionar', max_length=50, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='city_other',
            field=models.CharField(blank=True, default=' ', help_text='Em caso de outra cidade favor informa-la', max_length=80, verbose_name='Outra_cidade'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='course',
            field=models.CharField(blank=True, default=' ', help_text='CURSO (CASO ESTEJA NA ESCOLA TÉCNICA OU NA FACULDADE):', max_length=80, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='dedication',
            field=models.CharField(default=' ', max_length=50, verbose_name='dedicação'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='deficincy',
            field=models.CharField(default=' ', max_length=50, verbose_name='deficiente'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='deficincy_type',
            field=models.CharField(blank=True, default=' ', help_text='VOCÊ POSSUI ALGUM TIPO DE DEFICIÊNCIA? SE SIM, PODERIA NOS DIZER QUAL?', max_length=80, verbose_name='deficiencia'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='ethnicity',
            field=models.CharField(blank=True, default=' ', help_text='Clique para selecionar', max_length=50, null=True, verbose_name='etinia'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='ethnicity_other',
            field=models.CharField(blank=True, default=' ', help_text='Em caso de outra etinia favor informa-la', max_length=80, verbose_name='etinia'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='gender',
            field=models.CharField(choices=[('MC', 'Mulher cis'), ('MT', 'Mulher trans'), ('HC', 'Homem cis'), ('HT', 'Homem trans'), ('NB', 'Não binário'), ('OUT', 'Outra')], default=' ', help_text='Clique para selecionar', max_length=50, verbose_name='genero'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='gender_other',
            field=models.CharField(blank=True, default=' ', help_text='em casa de outro:', max_length=80, null=True, verbose_name='genero_outro'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='grade',
            field=models.CharField(default=' ', help_text='SE ESTIVER ESTUDANDO NESTE ANO, INFORME SÉRIE / PERÍODO:', max_length=80, verbose_name='Série'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='income',
            field=models.CharField(default=' ', help_text='RENDA FAMILIAR MENSAL', max_length=50, verbose_name='renda'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='intern',
            field=models.CharField(default=' ', max_length=50, verbose_name='Estágio'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='intern_time',
            field=models.CharField(blank=True, default=' ', help_text='CEM QUAIS HORÁRIOS VOCÊ TRABALHA OU FAZ ESTÁGIO? ', max_length=80, verbose_name='horarios'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='knowloge_other',
            field=models.CharField(blank=True, default=' ', help_text='COMO VOCÊ FICOU SABENDO DAS INSCRIÇÕES PARA O PROCESSO SELETIVO DESTE ANO? ', max_length=80, verbose_name='conhecimento'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='likes_to_draw',
            field=models.CharField(default=' ', max_length=50, verbose_name='desenha'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='looking_work',
            field=models.CharField(default=' ', max_length=50, verbose_name='trabalho'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='message',
            field=models.CharField(default=' ', help_text='USE AS LINHAS ABAIXO PARA DAR SEU RECADO: POR QUE VOCÊ SE INTERESSOU EM PARTICIPAR DO ESTÚDIO ESCOLA?', max_length=80, verbose_name='recado'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='neighberhood',
            field=models.CharField(default=' ', help_text='Bairro', max_length=80, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='parent',
            field=models.CharField(blank=True, default=' ', help_text='Nome completo do responsável ', max_length=80, verbose_name='Responsalvel'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='parent_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=' ', max_length=50, region=None, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='portifolio',
            field=models.CharField(default=' ', help_text='VOCÊ POSSUI UM LOCAL ONDE DIVULGA SEU TRABALHO ARTÍSTICO? EM CASO AFIRMATIVO COMPARTILHE O LINK COM A GENTE!', max_length=80, verbose_name='portifolio'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='previous_work',
            field=models.CharField(default=' ', help_text='HÁ OUTRA COISA QUE VOCÊ JÁ FEZ RELACIONADA À ANIMAÇÃO / AUDIOVISUAL QUE GOSTARIA DE DESTACAR?', max_length=80, verbose_name='experiencia'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='prior_course',
            field=models.CharField(blank=True, default=' ', max_length=50, verbose_name='curso_anterior'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='prior_course_year',
            field=models.CharField(blank=True, default=' ', max_length=50, verbose_name='curso_anterior'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='prior_inscription',
            field=models.CharField(default=' ', help_text='Clique para selecionar', max_length=80, verbose_name='inscricao_anterior'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='scholl_level',
            field=models.CharField(default=' ', help_text='NÍVEL DE ESCOLARIDADE:', max_length=50, verbose_name='escolaridade'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='school',
            field=models.CharField(default=' ', help_text='INSTITUIÇÃO DE ENSINO:', max_length=80, verbose_name='Escola'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='special_interview',
            field=models.CharField(blank=True, default=' ', help_text='SE SIM, PODERIA NOS DIZER QUAL?', max_length=80, verbose_name='cuidado_entrevista'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='special_need',
            field=models.CharField(default=' ', max_length=50, verbose_name='cuidado_especial'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='studing',
            field=models.CharField(default='Manhã', help_text='SE ESTIVER ESTUDANDO NESTE ANO, INFORME SÉRIE / PERÍODO:', max_length=50, verbose_name='período'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='zipcode',
            field=models.CharField(blank=True, default=' ', help_text='CEP do usuário', max_length=20, null=True),
        ),
    ]
