# Generated by Django 4.2.19 on 2025-02-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0005_alter_inscription_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='dedication',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='dedicação'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='prior_course',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='curso_anterior'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='prior_course_year',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='curso_anterior'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='prior_inscription',
            field=models.CharField(blank=True, default=' ', help_text='Clique para selecionar', max_length=80, null=True, verbose_name='inscricao_anterior'),
        ),
    ]
