# Generated by Django 4.2.19 on 2025-02-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0008_alter_inscription_critics_alter_inscription_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='critics',
            field=models.TextField(help_text='COMO VOCÊ LIDA COM CRÍTICAS EM RELAÇÃO AO SEU TRABALHO?', max_length=1000, verbose_name='criticas'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='message',
            field=models.TextField(default=' ', help_text='USE AS LINHAS ABAIXO PARA DAR SEU RECADO: POR QUE VOCÊ SE INTERESSOU EM PARTICIPAR DO ESTÚDIO ESCOLA?', max_length=1000, verbose_name='recado'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='portifolio',
            field=models.TextField(default=' ', help_text='VOCÊ POSSUI UM LOCAL ONDE DIVULGA SEU TRABALHO ARTÍSTICO? EM CASO AFIRMATIVO COMPARTILHE O LINK COM A GENTE!', max_length=1000, verbose_name='portifolio'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='previous_work',
            field=models.TextField(default=' ', help_text='HÁ OUTRA COISA QUE VOCÊ JÁ FEZ RELACIONADA À ANIMAÇÃO / AUDIOVISUAL QUE GOSTARIA DE DESTACAR?', max_length=1000, verbose_name='experiencia'),
        ),
    ]
