# Generated by Django 4.2.19 on 2025-02-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0009_alter_inscription_critics_alter_inscription_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='grade',
            field=models.CharField(blank=True, default=' ', help_text='SE ESTIVER ESTUDANDO NESTE ANO, INFORME SÉRIE / PERÍODO:', max_length=80, null=True, verbose_name='Série'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='studing',
            field=models.CharField(blank=True, default=' ', help_text='SE ESTIVER ESTUDANDO NESTE ANO, INFORME SÉRIE / PERÍODO:', max_length=50, null=True, verbose_name='período'),
        ),
    ]
