# Generated by Django 4.2.19 on 2025-03-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0010_alter_inscription_grade_alter_inscription_studing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='cpf',
            field=models.PositiveIntegerField(unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='rg',
            field=models.PositiveIntegerField(verbose_name='RG'),
        ),
    ]
