# Generated by Django 4.2.19 on 2025-03-04 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0012_alter_inscription_cpf_alter_inscription_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='cpf',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999999)], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='rg',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)], verbose_name='RG'),
        ),
    ]
