# Generated by Django 4.2.19 on 2025-03-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0014_alter_inscription_cpf_alter_inscription_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='cpf',
            field=models.BigIntegerField(unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='rg',
            field=models.BigIntegerField(verbose_name='RG'),
        ),
    ]
