# Generated by Django 4.2.19 on 2025-03-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0015_alter_inscription_cpf_alter_inscription_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='rg',
            field=models.CharField(verbose_name='RG'),
        ),
    ]
