# Generated by Django 4.2.19 on 2025-03-10 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0016_alter_inscription_rg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='address',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='course',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='likes_to_draw',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='rg',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='school',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='studing',
        ),
    ]
