# Generated by Django 4.2.19 on 2025-03-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0017_remove_inscription_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='tablet',
            field=models.CharField(default='OK', help_text='Clique para selecionar', max_length=200, verbose_name='tablet'),
        ),
    ]
