# Generated by Django 4.2.19 on 2025-03-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0018_alter_inscription_tablet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='age',
            field=models.CharField(default=' ', help_text='Clique para selecionar', max_length=80, verbose_name='idade'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='dedication',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True, verbose_name='dedicação'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='ethnicity',
            field=models.CharField(blank=True, default=' ', help_text='Clique para selecionar', max_length=150, null=True, verbose_name='etinia'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='frequency',
            field=models.CharField(default='MON', help_text='Clique para selecionar', max_length=90, verbose_name='frequencia'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='gender',
            field=models.CharField(default=' ', help_text='Clique para selecionar', max_length=150, verbose_name='genero'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='name',
            field=models.CharField(help_text='NOME COMPLETO (Nome Social para pessoas transgênero):\t', max_length=100, verbose_name='Nome'),
        ),
    ]
