# Generated by Django 4.2.19 on 2025-03-17 19:37

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0019_alter_inscription_age_alter_inscription_dedication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='age',
            field=models.CharField(default=' ', help_text='Clique para selecionar', verbose_name='idade'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='city',
            field=models.CharField(default='Rio de Janeiro', help_text='Clique para selecionar', verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='city_other',
            field=models.CharField(blank=True, default=' ', help_text='Em caso de outra cidade favor informa-la', verbose_name='Outra_cidade'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='critics',
            field=models.TextField(help_text='COMO VOCÊ LIDA COM CRÍTICAS EM RELAÇÃO AO SEU TRABALHO?', verbose_name='criticas'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='dedication',
            field=models.CharField(blank=True, default=' ', null=True, verbose_name='dedicação'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='deficincy',
            field=models.CharField(default=' ', verbose_name='deficiente'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='deficincy_type',
            field=models.CharField(blank=True, default=' ', help_text='VOCÊ POSSUI ALGUM TIPO DE DEFICIÊNCIA? SE SIM, PODERIA NOS DIZER QUAL?', verbose_name='deficiencia'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='ethnicity',
            field=models.CharField(blank=True, default=' ', help_text='Clique para selecionar', null=True, verbose_name='etinia'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='ethnicity_other',
            field=models.CharField(blank=True, default=' ', help_text='Em caso de outra etinia favor informa-la', verbose_name='etinia'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='family',
            field=models.CharField(default='2', help_text='Clique para selecionar', verbose_name='familia'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='frequency',
            field=models.CharField(default='MON', help_text='Clique para selecionar', verbose_name='frequencia'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='gender',
            field=models.CharField(default=' ', help_text='Clique para selecionar', verbose_name='genero'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='gender_other',
            field=models.CharField(blank=True, default=' ', help_text='em casa de outro:', null=True, verbose_name='genero_outro'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='income',
            field=models.CharField(default=' ', help_text='RENDA FAMILIAR MENSAL', verbose_name='renda'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='intern',
            field=models.CharField(default=' ', verbose_name='Estágio'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='intern_time',
            field=models.CharField(blank=True, default=' ', help_text='CEM QUAIS HORÁRIOS VOCÊ TRABALHA OU FAZ ESTÁGIO? ', verbose_name='horarios'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='knowloge',
            field=models.CharField(default='outros', help_text='Clique para selecionar', verbose_name='conhecia'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='knowloge_other',
            field=models.CharField(blank=True, default=' ', help_text='COMO VOCÊ FICOU SABENDO DAS INSCRIÇÕES PARA O PROCESSO SELETIVO DESTE ANO? ', verbose_name='conhecimento'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='looking_work',
            field=models.CharField(default=' ', verbose_name='trabalho'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='message',
            field=models.TextField(default=' ', help_text='USE AS LINHAS ABAIXO PARA DAR SEU RECADO: POR QUE VOCÊ SE INTERESSOU EM PARTICIPAR DO ESTÚDIO ESCOLA?', verbose_name='recado'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='name',
            field=models.CharField(help_text='NOME COMPLETO (Nome Social para pessoas transgênero):\t', verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='neighberhood',
            field=models.CharField(default=' ', help_text='Bairro', verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='parent',
            field=models.CharField(blank=True, default=' ', help_text='Nome completo do responsável ', verbose_name='Responsalvel'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='parent_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=' ', max_length=128, region=None, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='portifolio',
            field=models.TextField(default=' ', help_text='VOCÊ POSSUI UM LOCAL ONDE DIVULGA SEU TRABALHO ARTÍSTICO? EM CASO AFIRMATIVO COMPARTILHE O LINK COM A GENTE!', verbose_name='portifolio'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='previous_work',
            field=models.TextField(default=' ', help_text='HÁ OUTRA COISA QUE VOCÊ JÁ FEZ RELACIONADA À ANIMAÇÃO / AUDIOVISUAL QUE GOSTARIA DE DESTACAR?', verbose_name='experiencia'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='prior_course',
            field=models.CharField(blank=True, default=' ', null=True, verbose_name='curso_anterior'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='prior_course_year',
            field=models.CharField(blank=True, default=' ', null=True, verbose_name='curso_anterior'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='prior_inscription',
            field=models.CharField(blank=True, default=' ', help_text='Clique para selecionar', null=True, verbose_name='inscricao_anterior'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='scholl_level',
            field=models.CharField(default=' ', help_text='NÍVEL DE ESCOLARIDADE:', verbose_name='escolaridade'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='special_interview',
            field=models.CharField(blank=True, default=' ', help_text='SE SIM, PODERIA NOS DIZER QUAL?', verbose_name='cuidado_entrevista'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='special_need',
            field=models.CharField(default=' ', verbose_name='cuidado_especial'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='tablet',
            field=models.CharField(default='OK', help_text='Clique para selecionar', verbose_name='tablet'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='zipcode',
            field=models.CharField(blank=True, default=' ', help_text='CEP do usuário', null=True),
        ),
    ]
