# Generated by Django 4.2.19 on 2025-03-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0020_alter_inscription_age_alter_inscription_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='availability',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='disponibilidade'),
        ),
    ]
