# Generated by Django 4.2.19 on 2025-03-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0021_inscription_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='knowloge',
            field=models.TextField(default='outros', help_text='Clique para selecionar', verbose_name='conhecia'),
        ),
    ]
